# Configuration du site
title: Analyse Innovation et Salaires
description: Étude des liens entre innovation et salaires dans les entreprises
baseurl: ""
url: ""

# Configuration du thème
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Paramètres de compilation
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  
# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
